<?php
require_once('PHPMailer-master/class.phpmailer.php');
require('fpdf/fpdf.php');
include 'functions.php';

if ( !isset( $_SESSION['plan'] ) )
{
    header( 'Location: http://localhost/PROject/Loginpage.php' );
    exit();
}
$plan = $_SESSION['plan'];
$title = $_SESSION['title'];
if ( isset( $_SESSION['addr'] ) )
{
    $addr = $_SESSION['addr'];
}

class PDF extends FPDF {

    function Header()
    {
        // Logo
        $this->Image( 'img/help_cat_logo_2.jpg', 10, 6, 40, 18 );
        // Line break
        //$this->Ln( 10 );
        // Arial bold 15
        $this->SetFont( 'Arial', 'B', 16 );
        // Move to the right
        $this->Cell( 42 );
        // Title
        $this->Cell( 0, 10, $_SESSION['title'], 1, 0, 'C', false );
    }

    // Page footer
    function Footer()
    {
        // Position at 1.5 cm from bottom
        $this->SetY( -15 );
        // Arial italic 8
        $this->SetFont( 'Arial', 'I', 10 );
        // Page number
        //$this->Cell(0,10,'Page '.$this->PageNo().'/{nb}',0,0,'C');
        $this->Cell( 0, 10, 'PHP-PDF library by www.fpdf.org', 0, 0, 'C' );
    }

}

$pdf = new PDF();
$pdf->AddPage();
$pdf->SetFont( 'Courier', '', 11 );
$pdf->Ln( 10 );
$pdf->Cell( 0, 5, "generated by the STUNNER", 0, 1, 'C' );
$pdf->Ln( 5 );

for ( $row = 0; $row < count( $plan ); $row++ )
{
    if ( isset( $plan[$row][1] ) )
    {
    $pdf->SetFont( 'Arial', 'B', 14 );
    $pdf->Cell( 0, 10, $plan[$row][0], 'T', 1, 'C' );
    $pdf->SetFont( 'Arial', '', 12 );
    for ( $col = 1; $col < sizeOf( $plan[$row] ); $col++ )
    {
        $pdf->Cell( 5 ); //left indent        
        if ( strpos( $plan[$row][$col], 'INTERNSHIP' ) !== false )
        {   //special font for internship
            $pdf->SetFont( 'Arial', 'I', 15 );
            $pdf->Cell( 0, 5, $plan[$row][$col], 0, 1, 'L' );
            $pdf->SetFont( 'Arial', '', 12 );
        }
        else if (trim($plan[$row][$col]) !== '')
        {
            $pdf->Cell( 0, 5, $plan[$row][$col], 0, 1, 'L' );
        }
    }
    $pdf->Ln( 2 );
    }
}
$pdf->Cell( 0, 10, " ", 'T', 1, 'C' );
$attachment = $pdf->Output( 'S' ); //generate PDF as email attachment

$email = new PHPMailer( true );
//$err = "";
try
{
    $email->From = 'helpcat.stunner@gmail.com';
    $email->FromName = 'the STUNNER';
    $email->Subject = "$title";
    $email->Body = "Dear " . substr( $_SESSION['student'], 0, -11 ) //remove studentID from student string 
            . ",\n\n Attached in this e-mail is your computer-generated study plan, powered by the STUNNER.";
    $email->AddAddress( $addr );
    $email->AddStringAttachment( $attachment, "$title.pdf" );
    $email->Send();
} catch (phpmailerException $e)
{
    header( "Location: http://localhost/PROject/PlanPage.php?mail=".$e->errorMessage() );
    exit();
}
header( 'Location: http://localhost/PROject/PlanPage.php?mail=sent' );
exit();
?>
<html>
    <head>
        <title>STUNNER...</title>
        <link rel="stylesheet" type="text/css" href="style.css" />
    </head>
    <body class="color">
        <div class="top"></div>
        <h1><?php echo $e; ?></h1>
    </body>
</html>