<?php

require('fpdf/fpdf.php');
include 'functions.php';

$plan = $_SESSION['plan'];
$title = $_SESSION['title'];

class PDF extends FPDF {

    function Header()
    {
        // Logo
        $this->Image( 'img/help_cat_logo_2.jpg', 10, 6, 40, 18 );
        // Line break
        //$this->Ln( 10 );
        // Arial bold 15
        $this->SetFont( 'Arial', 'B', 16 );
        // Move to the right
        $this->Cell( 42 );
        // Title
        $this->Cell( 0, 10, $_SESSION['title'], 1, 0, 'C', false );
    }

    // Page footer
    function Footer()
    {
        // Position at 1.5 cm from bottom
        $this->SetY( -15 );
        // Arial italic 8
        $this->SetFont( 'Arial', 'I', 10 );
        // add Page number with code below if necessary
        //$this->Cell(0,10,'Page '.$this->PageNo().'/{nb}',0,0,'C');
        $this->Cell( 0, 10, 'PHP-PDF library by www.fpdf.org', 0, 0, 'C' );
    }

}

$pdf = new PDF();
$pdf->AddPage();
$pdf->SetFont( 'Courier', '', 11 );
$pdf->Ln( 10 );
$pdf->Cell( 0, 5, "generated by the STUNNER", 0, 1, 'C' );
$pdf->Ln( 5 );

for ( $row = 0; $row < count( $plan ); $row++ )
{
    if ( isset( $plan[$row][1] ) )
    {
    $pdf->SetFont( 'Arial', 'B', 14 );
    $pdf->Cell( 0, 10, $plan[$row][0], 'T', 1, 'C' );
    $pdf->SetFont( 'Arial', '', 12 );
    for ( $col = 1; $col < sizeOf( $plan[$row] ); $col++ )
    {
        $pdf->Cell( 5 ); //left indent        
        if ( strpos( $plan[$row][$col], 'INTERNSHIP' ) !== false )
        {   //special font for internship
            $pdf->SetFont( 'Arial', 'I', 15 );
            $pdf->Cell( 0, 5, $plan[$row][$col], 0, 1, 'L' );
            $pdf->SetFont( 'Arial', '', 12 );
        }
        else if (trim($plan[$row][$col]) !== '')
        {
            $pdf->Cell( 0, 5, $plan[$row][$col], 0, 1, 'L' );
        }
    }
    $pdf->Ln( 2 );
    }
}
$pdf->Cell( 0, 10, " ", 'T', 1, 'C' );
$pdf->Output( 'I', "$title.pdf" );
?>